version: "3"
services:
  postgres:
    container_name: postgres
    build: 
      context: .
      dockerfile: ./database/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    image: ghcr.io/segre5458/le4db/postgres:latest
  app:
    container_name: app
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    tty: true 
    image: ghcr.io/segre5458/le4db/app:latest
  frontend-react:
    container_name: frontend-react
    build: 
      context: .
      dockerfile: ./frontend-react/Dockerfile
    volumes:
      - ./frontend-react/src:/frontend-react/src
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - app
    links:
      - postgres
      - app
    tty: true
    image: ghcr.io/segre5458/le4db/frontend-react:latest

