version: "3"
services:
  postgres:
    container_name: postgres
    build: 
      context: .
      dockerfile: ./database/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  app:
    container_name: app
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    tty: true 
  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/app:cached
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - app
    links:
      - app
    tty: true
volumes:
  node_modules:
    

