version: "3"
services:
  postgres:
    container_name: postgres
    build: 
      context: .
      dockerfile: ./database/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  app:
    container_name: app
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    tty: true 
